export const MUNICIPALITIES = [
  "Aeugst am Albis",
  "Affoltern am Albis",
  "Bonstetten",
  "Hausen am Albis",
  "Hedingen",
  "Kappel am Albis",
  "Knonau",
  "Maschwanden",
  "Mettmenstetten",
  "Obfelden",
  "Ottenbach",
  "Rifferswil",
  "Stallikon",
  "Wettswil am Albis",
  "Benken (ZH)",
  "Berg am Irchel",
  "Buch am Irchel",
  "Dachsen",
  "Dorf",
  "Feuerthalen",
  "Flaach",
  "Flurlingen",
  "Henggart",
  "Kleinandelfingen",
  "Laufen-Uhwiesen",
  "Marthalen",
  "Ossingen",
  "Rheinau",
  "Thalheim an der Thur",
  "Trüllikon",
  "Truttikon",
  "Volken",
  "Bachenbülach",
  "Bassersdorf",
  "Bülach",
  "Dietlikon",
  "Eglisau",
  "Embrach",
  "Freienstein-Teufen",
  "Glattfelden",
  "Hochfelden",
  "Höri",
  "Hüntwangen",
  "Kloten",
  "Lufingen",
  "Nürensdorf",
  "Oberembrach",
  "Opfikon",
  "Rafz",
  "Rorbas",
  "Wallisellen",
  "Wasterkingen",
  "Wil (ZH)",
  "Winkel",
  "Bachs",
  "Boppelsen",
  "Buchs (ZH)",
  "Dällikon",
  "Dänikon",
  "Dielsdorf",
  "Hüttikon",
  "Neerach",
  "Niederglatt",
  "Niederhasli",
  "Niederweningen",
  "Oberglatt",
  "Oberweningen",
  "Otelfingen",
  "Regensberg",
  "Regensdorf",
  "Rümlang",
  "Schleinikon",
  "Schöfflisdorf",
  "Stadel",
  "Steinmaur",
  "Weiach",
  "Bäretswil",
  "Bubikon",
  "Dürnten",
  "Fischenthal",
  "Gossau (ZH)",
  "Grüningen",
  "Hinwil",
  "Rüti (ZH)",
  "Seegräben",
  "Wald (ZH)",
  "Wetzikon (ZH)",
  "Adliswil",
  "Kilchberg (ZH)",
  "Langnau am Albis",
  "Oberrieden",
  "Richterswil",
  "Rüschlikon",
  "Thalwil",
  "Erlenbach (ZH)",
  "Herrliberg",
  "Hombrechtikon",
  "Küsnacht (ZH)",
  "Männedorf",
  "Meilen",
  "Oetwil am See",
  "Stäfa",
  "Uetikon am See",
  "Zumikon",
  "Zollikon",
  "Fehraltorf",
  "Hittnau",
  "Lindau",
  "Pfäffikon",
  "Russikon",
  "Weisslingen",
  "Wila",
  "Wildberg",
  "Dübendorf",
  "Egg",
  "Fällanden",
  "Greifensee",
  "Maur",
  "Mönchaltorf",
  "Schwerzenbach",
  "Uster",
  "Volketswil",
  "Wangen-Brüttisellen",
  "Altikon",
  "Brütten",
  "Dägerlen",
  "Dättlikon",
  "Dinhard",
  "Ellikon an der Thur",
  "Elsau",
  "Hagenbuch",
  "Hettlingen",
  "Neftenbach",
  "Pfungen",
  "Rickenbach (ZH)",
  "Schlatt (ZH)",
  "Seuzach",
  "Turbenthal",
  "Winterthur",
  "Zell (ZH)",
  "Aesch (ZH)",
  "Birmensdorf (ZH)",
  "Dietikon",
  "Geroldswil",
  "Oberengstringen",
  "Oetwil an der Limmat",
  "Schlieren",
  "Uitikon",
  "Unterengstringen",
  "Urdorf",
  "Weiningen (ZH)",
  "Zürich",
  "Andelfingen",
  "Stammheim",
  "Wädenswil",
  "Elgg",
  "Horgen",
  "Illnau-Effretikon",
  "Bauma",
  "Wiesendangen",
]
