# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v6

      - name: Set up Node.js and pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
          install: true

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: pnpm run storybook:build
          path: docs
          checkout: false
